### PR TITLE
Add glyphs to fix Hash collision with bigint and string 

### LINKED ISSUE #2496: Hash collision with bigint and string in `@solana/fast-stable-stringify`
#2482 added native bigint support to the hasher, but now these two datastructures produce the same hash:

```ts
stringify({foo: 10n});
stringify({foo: "10n"});
```

We need a solution for this. Since the hash doesn't have to be valid JSON, we should be able to use a prefix/suffix on the key/value pair. 

Test case: https://codesandbox.io/p/devbox/goofy-shadow-jsnpv3

### PR DESCRIPTION
**Pull request by Hrushi20**
Support BigInt and added more tests. Putting Glyph outside the quote avoid collisions. 

```
s(100n) // "100"n
s({foo: 100n}) // {"foo":"100"n}
```

Closes #2496.

### CODE REVIEW

File: packages/fast-stable-stringify/src/index.ts [hunk 1]
```diff
@@ -61,7 +61,7 @@ function stringify(val: unknown, isArrayProp: boolean) {
         case 'undefined':
             return isArrayProp ? null : undefined;
         case 'bigint':
-            return JSON.stringify(val.toString() + 'n');
+            return JSON.stringify(val.toString()) + 'n';
```
Comment (steveluscher) [inline packages/fast-stable-stringify/src/index.ts:64]: Looks great! Can you think of a reason why we still need the `"` character though? Can we just do ```${val.toString()}n``` and have it work?

Comment (Hrushi20) [reply packages/fast-stable-stringify/src/index.ts]: Fixed it.

**Review by steveluscher — APPROVED** [review]
Added via Giphy
