### PR TITLE
`SolanaErrors` with a nested `cause` now specify the `cause` property as `SolanaError | undefined`

### LINKED ISSUE #2959: The type of `SolanaError<SOLANA_ERROR__JSON_RPC__SERVER_ERROR_SEND_TRANSACTION_PREFLIGHT_FAILURE>` must have `cause?: SolanaError` as part of its type
## Steps to reproduce

```ts
if (isSolanaError(e, SOLANA_ERROR__JSON_RPC__SERVER_ERROR_SEND_TRANSACTION_PREFLIGHT_FAILURE)) {
    console.log(e.cause?.message); // TYPE ERROR: Property 'message' does not exist on type 'unknown'
}
```

### PR DESCRIPTION
**Pull request by steveluscher**
Closes #2959.

### CODE REVIEW

**Comment by steveluscher** [comment]
* **#2964** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2964?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @steveluscher and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: packages/errors/src/error.ts [hunk 1]
```diff
@@ -24,6 +24,7 @@ type SolanaErrorCodedContext = Readonly<{
 
 export class SolanaError<TErrorCode extends SolanaErrorCode = SolanaErrorCode> extends Error {
     readonly context: SolanaErrorCodedContext[TErrorCode];
+    readonly cause?: TErrorCode extends SolanaErrorCodeWithCause ? SolanaError : unknown;
```
Comment (lorisleiva) [inline packages/errors/src/error.ts:27]: I don't know that this is enough considering the tests are now failing to assert on the `cause` attribute.

I think we need to explicitly set the `cause` property on the constructor instead of expected the parent constructor to set it for us.

**Review by lorisleiva — CHANGES_REQUESTED** [review]
Happy with the types but there seems to be an issue with the logic.

File: packages/errors/src/error.ts (hunk 1 above)
Comment (steveluscher) [reply packages/errors/src/error.ts:27]: Oh, oops. Yes; I meant for those to be type annotations only.

Comment (steveluscher) [reply packages/errors/src/error.ts:27]: Mmmm… weird. No, that should have worked.

https://www.typescriptlang.org/play/?#code/MYGwhgzhAEDCD28QFEBOr6ugUwB4BdsA7AExjQywG8Aoae6VbME+IkAT2mDAFcJsAfgBc0IrwC2AI2xYAPtF6lsAMwCWRbCQDcdBsDYR8qXsHyYAFADobYVAHMIASmi0G76BF4AHWddsOznr0AL40YTQGREbQYNAAvGLYAO5wiCjolgDkUixZADSuPPzYogCMAEwAzCFOulEQSNhWIPD2FmBWxQJOQA

Comment (steveluscher) [reply packages/errors/src/error.ts:27]: Uh, the TypeScript compiler literally produces the same JavaScript with or without that line.

Comment (steveluscher) [reply packages/errors/src/error.ts:27]: Oof. https://github.com/egoist/tsup/issues/1104

Comment (steveluscher) [reply packages/errors/src/error.ts:27]: 😢 https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier

File: packages/errors/src/error.ts [hunk 2]
```diff
@@ -23,6 +23,7 @@ type SolanaErrorCodedContext = Readonly<{
 }>;
 
 export class SolanaError<TErrorCode extends SolanaErrorCode = SolanaErrorCode> extends Error {
+    readonly cause?: TErrorCode extends SolanaErrorCodeWithCause ? SolanaError : unknown = this.cause;
```
[the remark this answers is not in the document]
Comment (lorisleiva) [reply packages/errors/src/error.ts:26]: TIL
